server {
    listen 80;

    root /var/www/html;
    index index.php index.html;

    #
    # /hello-world
    #
    location /hello-world {
        try_files $uri $uri/ /endpoints/hello-world/public/index.php?$query_string;
    }

    location ^~ /endpoints/hello-world/public/index.php {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }

    location ~* \.(php)$ {
        fastcgi_pass php:9000;
    }
}
